### ISSUE TITLE
Getting "Fatal Error: Invalid URL, remove all non alphanumeric charracters" after fresh setup

### ISSUE THREAD

**Issue by GregsGrog** [marianocarrazana/OnePagePHP#2]
I have setup on a windows localhost machine and I am getting a "Fatal Error: Invalid URL, remove all non alphanumeric charracters" error when trying to access index.html.

This is my config setup

`{
    "paths": {
        "views": "src/views",
        "controllers": "src/controllers",
        "sections": "src/sections"
    },
    "default_title": "OnePage",
    "site_url": "//localhost/OnePagePHP",
    "eval_scripts": true,
    "automatic_render": true,
    "enable_router": true,
    "root_dir": "/test/OnePagePHP",
    "templates_extension": "html"
}`

And this is the error
![image](https://user-images.githubusercontent.com/22116310/68391216-f6f49880-015e-11ea-9d8d-95441ba8e74b.png)

**Comment by marianocarrazana** [comment]
I think is fixed now, try again please

**Comment by GregsGrog** [comment]
Ok it seems to now be loading pages but doesn't render them, I get a black white screen when going to either "index.html" or "mypage.html" after following setup.

**Comment by marianocarrazana** [comment]
What URL are you using to access to "mypage.html"?
remember to use the name of the file without the extension, for access to "mypage.html" you need to use "mysite.com/mypage" for "index.html" you can access with "mysite.com/" or "mysite.com/index"

**Comment by GregsGrog** [comment]
Correct im using localhost/ to access index and just getting a blank screen with no errors to access "mypage" im using "localhost/mypage"

**Comment by marianocarrazana** [comment]
first change "site_url": "//localhost/OnePagePHP" to "site_url": "//localhost" in the config.json
reload the page, if is not working yet put the last lines from last minutes from your error.log file(if you dont know where to find it [read this](https://stackoverflow.com/questions/5127838/where-does-php-store-the-error-log-php5-apache-fastcgi-cpanel))

**Comment by GregsGrog** [comment]
Ok I think I might have got a little closer to the issue, may I ask are you testing on windows linux or mac? Because I think the issue might be due to directory separators.

I tried what you suggested and it unfortunately did not work, upon checking the php logs there seems to be no new entries.

**Comment by marianocarrazana** [comment]
probably is the directory separator, i'll check it in windows in a few hours

**Comment by marianocarrazana** [comment]
Try the new version, I tested it in windows and ubuntu

**Comment by GregsGrog** [comment]
Perfect this is now working!
